export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';